### PR TITLE
Fixed options propagation to cpp-client #13

### PR DESCRIPTION
**Pull request by rigazilla**
Fix for #13 
Now valgrind can be disabled via env var:
````
NOENABLE_VALGRIND=ON pip3 -v wheel .
````

### CODE REVIEW

**Comment by gilv** [comment]
@rigazilla @tristantarrant this patch did the trick and no more valgrind issues. However i get different errors ( at later stage ). 

/usr/local/include/google/protobuf/stubs/port.h:114:2: error: "Protobuf requires at least C++11."
  #error "Protobuf requires at least C++11."

What are the version requirements for the dependencies?

**Comment by gilv** [comment]
i have protoc 3.11.1 and cmake 3.16

**Comment by gilv** [comment]
so i used `NOENABLE_VALGRIND=ON CXX_STD=C++11 CXXFLAGS='-std=c++11' pip3 -v wheel .`

but it still failed.. with other errors

                                 ^
  In file included from /private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-sctr_wgv/build/cpp-client/src/cppclient/src/hotrod/impl/protocol/HeaderParams.cpp:3:
  In file included from /private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-sctr_wgv/build/cpp-client/src/cppclient/src/hotrod/impl/protocol/HeaderParams.h:5:
  /private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-sctr_wgv/build/cpp-client/src/cppclient/include/infinispan/hotrod/DataFormat.h:27:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
          std::string subType;
                      ^
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:210:32: note: template is declared here
      class _LIBCPP_TEMPLATE_VIS basic_string;
                                 ^
  In file included from /private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-sctr_wgv/build/cpp-client/src/cppclient/src/hotrod/impl/protocol/HeaderParams.cpp:3:
  In file included from /private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-sctr_wgv/build/cpp-client/src/cppclient/src/hotrod/impl/protocol/HeaderParams.h:5:
  /private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-sctr_wgv/build/cpp-client/src/cppclient/include/infinispan/hotrod/DataFormat.h:28:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
          std::string typeSubtype;

**Comment by gilv** [comment]
@rigazilla ^^ thanks

**Comment by rigazilla** [comment]
@gilv I think [this](https://stackoverflow.com/questions/19223360/implicit-instantiation-of-undefined-template-stdbasic-stringchar-stdchar) could be a fix.
Can add the headers to the `src/cppclient/include/infinispan/hotrod/DataFormat.h` as explained and try a build of the c++ library?

It should be easy:
````
git clone https://github.com/infinispan/cpp-client.git
cd cpp-client
<apply the fix>
mkdir build && cd build
cmake .. -DNOENABLE_VALGRIND=ON
make hotrod
````

Unfortunately I don't have a mac setup available atm.

**Comment by gilv** [comment]
@rigazilla how to enable C++11 for cpp-client?

**Comment by rigazilla** [comment]
> @rigazilla how to enable C++11 for cpp-client?

It should be enable by default for gcc and clang.
Try setting `CXX_STD=C++11 CXXFLAGS='-std=c++11'` in the env as you did above

**Comment by gilv** [comment]
@rigazilla I am sorry, i am a bit rusty with C things...how to set those flags here? I tried to add them to cmake and also make...and it doesn't work. Can you please be more specific, what command should i run to enable those flags for cpp-client?

**Comment by rigazilla** [comment]
> @rigazilla I am sorry, i am a bit rusty with C things...how to set those flags here? I tried to add them to cmake and also make...and it doesn't work. Can you please be more specific, what command should i run to enable those flags for cpp-client?

No problem,

try this:
````
git clone https://github.com/infinispan/cpp-client.git
cd cpp-client
<apply the fix>
mkdir build && cd build
export CXX_STD=C++11 CXXFLAGS='-std=c++11'
cmake .. -DNOENABLE_VALGRIND=ON
make hotrod
````

**Comment by gilv** [comment]
@rigazilla thanks...it now failed with something else

[ 50%] Building CXX object CMakeFiles/hotrod.dir/src/hotrod/impl/protocol/HeaderParams.cpp.o
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/protocol/HeaderParams.cpp:3:
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/protocol/HeaderParams.h:5:
/Users/gilv/Dev/cpp-client/include/infinispan/hotrod/DataFormat.h:26:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
        std::string type;
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:210:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/protocol/HeaderParams.cpp:3:
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/protocol/HeaderParams.h:5:
/Users/gilv/Dev/cpp-client/include/infinispan/hotrod/DataFormat.h:27:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
        std::string subType;
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:210:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/protocol/HeaderParams.cpp:3:
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/protocol/HeaderParams.h:5:
/Users/gilv/Dev/cpp-client/include/infinispan/hotrod/DataFormat.h:28:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
        std::string typeSubtype;
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:210:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/protocol/HeaderParams.cpp:3:
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/protocol/HeaderParams.h:5:
/Users/gilv/Dev/cpp-client/include/infinispan/hotrod/DataFormat.h:31:14: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
        std::string toString() const {
                    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:210:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;
                               ^
4 errors generated.
make[3]: *** [CMakeFiles/hotrod.dir/src/hotrod/impl/protocol/HeaderParams.cpp.o] Error 1
make[2]: *** [CMakeFiles/hotrod.dir/all] Error 2
make[1]: *** [CMakeFiles/hotrod.dir/rule] Error 2
make: *** [hotrod] Error 2

**Comment by rigazilla** [comment]
Hi @gilv, the comments history confuses me.

For the error above, did you try to apply this:

> @gilv I think [this](https://stackoverflow.com/questions/19223360/implicit-instantiation-of-undefined-template-stdbasic-stringchar-stdchar) could be a fix.
> Can add the headers to the `src/cppclient/include/infinispan/hotrod/DataFormat.h` as explained and try a build of the c++ library?
> 
> It should be easy:
> 
> ```
> git clone https://github.com/infinispan/cpp-client.git
> cd cpp-client
> <apply the fix>
> mkdir build && cd build
> cmake .. -DNOENABLE_VALGRIND=ON
> make hotrod
> ```
> 
> Unfortunately I don't have a mac setup available atm.

**Comment by gilv** [comment]
@rigazilla I agree...the history confuses me as well ;) 
 You advised me to built cpp-client instead of python client. I used steps as you suggested

git clone https://github.com/infinispan/cpp-client.git
cd cpp-client
<apply the fix>
mkdir build && cd build
export CXX_STD=C++11 CXXFLAGS='-std=c++11'
cmake .. -DNOENABLE_VALGRIND=ON
make hotrod

it fails. What headers i need to add where to build cpp client? Thanks

**Comment by rigazilla** [comment]
ok, thanks for the recap :) 

so the error you have now:
> /Users/gilv/Dev/cpp-client/include/infinispan/hotrod/DataFormat.h:26:14: error: implicit instantiation of ...

is probably due to a difference in the C++11 headers between linux and mac (are you using clang right?).
[this](https://stackoverflow.com/questions/19223360/implicit-instantiation-of-undefined-template-stdbasic-stringchar-stdchar) seems a good description of the problem.

You should edit `/Users/gilv/Dev/cpp-client/include/infinispan/hotrod/DataFormat.h` and add the header files as described in the answer.
The final result should be:
````
/*
 * DataFormat.h
 *
 *  Created on: Sep 6, 2018
 *      Author: rigazilla
 */

#ifndef INCLUDE_INFINISPAN_HOTROD_DATAFORMAT_H_
#define INCLUDE_INFINISPAN_HOTROD_DATAFORMAT_H_

#include "infinispan/hotrod/ImportExport.h"
#include "infinispan/hotrod/Marshaller.h"

#include <map>
#include <vector>
#include <memory>
// Additional headers
#include <string>
#include <sstream>
#include <iostream>

namespace infinispan {
namespace hotrod {
.....
````

**Comment by gilv** [comment]
@rigazilla am i the only one who uses Mac to build this client and mac is not supported? Do you have may be a REST client i can use for Infinispan?

Did as you suggested above

In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/event/EventDispatcher.cpp:8:
In file included from /Users/gilv/Dev/cpp-client/src/hotrod/impl/event/EventDispatcher.h:13:
/Users/gilv/Dev/cpp-client/include/infinispan/hotrod/CounterEvent.h:64:39: warning: unused parameter 'counterName' [-Wunused-parameter]
    CounterListener(const std::string counterName, std::function<void(const CounterEvent)> action) :
                                      ^
/Users/gilv/Dev/cpp-client/include/infinispan/hotrod/CounterEvent.h:67:39: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>,
      std::__1::allocator<char> >'
    CounterListener(const std::string counterName) :
                                      ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:210:32: note: template is declared here
    class _LIBCPP_TEMPLATE_VIS basic_string;

**Comment by rigazilla** [comment]
@gilv you should apply the same fix to `/Users/gilv/Dev/cpp-client/include/infinispan/hotrod/CounterEvent.h`.
Probably the C++11 headers are differents in mac toolchain.
Can you send me the full log of the commands:
````
export CXX_STD=C++11 CXXFLAGS='-std=c++11'
cmake .. -DNOENABLE_VALGRIND=ON
make hotrod
````
I want to see the settings and maybe try to reproduce the error.

Yeah Infinispan has also a REST endpoint documented [here](https://infinispan.org/docs/stable/titles/rest/rest.html#rest_v2_api)

**Comment by rigazilla** [comment]
@gilv I think I've fixed the build on Mac, can you try a run?

**Comment by gilv** [comment]
@rigazilla all seems worked fine, it build and i did install.
gilv1-mac:python-client gilv$ pip3 install *.whl
Processing ./infinispan-0.1-cp36-cp36m-macosx_10_15_x86_64.whl
Installing collected packages: infinispan
Successfully installed infinispan-0.1

where is lib located?

I tried 

gilv1-mac:python-client gilv$ LD_LIBRARY_PATH=/usr/local/lib python3 test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from Infinispan import Infinispan
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/Infinispan/Infinispan.py", line 13, in <module>
    from . import _Infinispan
ImportError: dlopen(/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/Infinispan/_Infinispan.so, 2): Library not loaded: /private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-nr1hqqh0/build/cpp-client/src/cppclient-build/libhotrod.1.0.dylib
  Referenced from: /Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/Infinispan/_Infinispan.so
  Reason: image not found

**Comment by rigazilla** [comment]
@gilv try with `pip3 show -f infinispan` you can see the install location and the relative path for all the files.
In my env I have:
````
Location: /usr/local/lib/python3.7/site-packages
Requires: 
Required-by: 
Files:
  ../../libhotrod.1.0.dylib
  Infinispan/Infinispan.py
  Infinispan/_Infinispan.so
  Infinispan/__pycache__/Infinispan.cpython-37.pyc
  infinispan-0.1.dist-info/INSTALLER
  infinispan-0.1.dist-info/METADATA
  infinispan-0.1.dist-info/RECORD
  infinispan-0.1.dist-info/WHEEL
  infinispan-0.1.dist-info/top_level.txt
````
and for a `pip3 install --user`

````
Location: /Users/rigazilla/Library/Python/3.7/lib/python/site-packages
Requires: 
Required-by: 
Files:
  ../../libhotrod.1.0.dylib
  Infinispan/Infinispan.py
  Infinispan/_Infinispan.so
  Infinispan/__pycache__/Infinispan.cpython-37.pyc
  infinispan-0.1.dist-info/INSTALLER
  infinispan-0.1.dist-info/METADATA
  infinispan-0.1.dist-info/RECORD
  infinispan-0.1.dist-info/WHEEL
  infinispan-0.1.dist-info/top_level.txt
````
Seems that you're installing with the `--user` configuration so you need something like:
`DYLD_LIBRARY_PATH=/Users/gilv/.pyenv/versions/3.6.7/lib python3 test.py`
Macos uses `DYLD_LIBRARY_PATH` instead of `LD_LIBRARY_PATH` to set the library search path.

**Comment by gilv** [comment]
gilv1-mac:python-client gilv$ pip show -f infinispan 
Name: infinispan
Version: 0.1
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: UNKNOWN
Location: /Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages
Requires: 
Required-by: 
Files:
  ../../libhotrod.1.0.dylib
  Infinispan/Infinispan.py
  Infinispan/_Infinispan.so
  Infinispan/__pycache__/Infinispan.cpython-36.pyc
  infinispan-0.1.dist-info/INSTALLER
  infinispan-0.1.dist-info/METADATA
  infinispan-0.1.dist-info/RECORD
  infinispan-0.1.dist-info/WHEEL
  infinispan-0.1.dist-info/top_level.txt


gilv1-mac:python-client gilv$ DYLD_LIBRARY_PATH=/Users/gilv/.pyenv/versions/3.6.7/lib python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from Infinispan import Infinispan
  File "/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/Infinispan/Infinispan.py", line 13, in <module>
    from . import _Infinispan
ImportError: dlopen(/Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/Infinispan/_Infinispan.so, 2): Library not loaded: /private/var/folders/nw/kg5kt9150nj48738r5wz9ly80000gn/T/pip-req-build-nr1hqqh0/build/cpp-client/src/cppclient-build/libhotrod.1.0.dylib
  Referenced from: /Users/gilv/.pyenv/versions/3.6.7/lib/python3.6/site-packages/Infinispan/_Infinispan.so
  Reason: image not found
gilv1-mac:python-client gilv$ 

@rigazilla

**Comment by rigazilla** [comment]
@gilv, it seems you ran into the SIP problem. If SIP is enable you can't change any DYLD_* env variable.
Quick solutions could be:
[disable SIP](https://github.com/nteract/nteract/issues/1523#issuecomment-284027093)
[symlink the libs into "usual" path](https://github.com/nteract/nteract/issues/1523#issuecomment-301623519)

**Comment by tristantarrant** [comment]
when installed globally you probably need to `sudo update_dyld_shared_cache`

**Pull request merged**
